version: "3"

services:

  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=softing
      - MYSQL_USER=softing
      - MYSQL_PASSWORD=softing
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    restart: unless-stopped
    depends_on:
      - mysql
    entrypoint: "/tmp/wait-for-it.sh mysql:3306 -- /tmp/run.sh"
    environment:
      - APP_NAME=Softing
      - APP_KEY=base64:634ZiSdi+uhL+q/kSvdEHFT5xMWFUGkE6J8CpGMw/Ig=
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - APP_TIMEZONE=UTC
      - LOG_CHANNEL=stack
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=softing
      - DB_USERNAME=softing
      - DB_PASSWORD=softing

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - mysql
      - app
